### ISSUE TITLE
Increase label sizes

### ISSUE THREAD

**Issue by ugurdogrusoz** [metincansiper/SBGNViz_CoSE#4]
Please try to improve this in line with my conversation with Mecit.

UD: Sample model'lerde label font size'lari iyi de, disaridan yukledigimiz (ozellikle Begum'un tezi icin ChiBE ile urettigi) sbgnml'ler acilinca font'lari cok kucuk kaliyor. Hatta node'larin label'lari cok kucukken compoundlarin (compaortment) asiri buyuk oluyor. Bu konuda ne yapabiliriz?

MS: ben width in 3 te birine oturtacak sekilde fontu küçült diye yazmıstım diye hatırlıyorum, orada bir if yazılabilir, 3 te biri belirli bir sayıdan küçük ise default bir font size a set edilebilir, ama güzel de durmayabilir böyle. compartment ların font size ını ben ayarlamıyorum zaten default shape kullanıyordum, cytoscape nasıl yazıyorsa oyle o. style sheet te biz bir font size da geçirmiş olabiliriz tabi.

```
$$.sbgn.drawDynamicLabelText = function(context, textProp){
    var textHeight = parseInt(textProp.height/3);
    textProp.color = "#0f0f0f";
    textProp.font = textHeight + "px Arial";
    $$.sbgn.drawText(context, textProp);
};
```

bu kod cytoscape.renderer.canvas.sbgn-renderer da bulunmakta. belki 3 yerine 2.5 filan yazılsa güzel durabilir hocam. (UD: let's try 2.0 if it's not too bad).

**Comment by ugurdogrusoz** [comment]
This should actually be done in PathwayCommons/sbgnviz-js, not here!

**Comment by ayhun** [comment]
We are taking these results. how should we proceed? http://imgur.com/a/jPK25

**Comment by ugurdogrusoz** [comment]
Are the 3 screenshots reflecting ratios 2, 2.5, and 3, respectively? I like the first one best since it's much more readable. But we need to:
1) make sure this size is acceptable in other models (at least the sample ones). it could be a problem with models where there are many info or state boxes of nodes.
2) we should increase the font size in info and state boxes respectively as well.

**Comment by ayhun** [comment]
Hocam dosya ismine göre sıralar diye düşünmüştük öyle olmamış heralde. Sıralama 2.5, 3, 2 diye gidiyor. Istediğiniz gibi 2.5 yaptık fakat bazı nodelarda label tamamen çıkmıyor böyle büyütünce. Örneğin ilk resimdeki Hsg70 Hs... diye çıkmış. Onun dışında daha güzel görünüyor.

**Comment by ugurdogrusoz** [comment]
I've done a little experimenting myself with this. It's a tradeoff between readability through node size and readability through visible label length. I think 2.3 is a good compromise; let's go with that!

**Comment by ugurdogrusoz** [comment]
Right after this piece of code we also have calculations for font size for info and state boxes, let's please change those as well as follows (see where I have a comment with "UD: ...")

```
$$.sbgn.drawStateText = function(context, textProp){
    var stateValue = textProp.state.value;
    var stateVariable = textProp.state.variable;

    var stateLabel = (stateVariable == null /*|| typeof stateVariable === undefined */) ? stateValue : 
        stateValue + "@" + stateVariable;

    var fontSize = parseInt(textProp.height/1.5); //UD: changed! was 2.0

    textProp.font = fontSize + "px Arial";
    textProp.label = stateLabel;
    textProp.color = "#0f0f0f";
    $$.sbgn.drawText(context, textProp);
};

$$.sbgn.drawInfoText = function(context, textProp){
    var fontSize = parseInt(textProp.height/1.5); //UD: changed! was 2.0
    textProp.font = fontSize + "px Arial";
    textProp.color = "#0f0f0f";
    $$.sbgn.drawText(context, textProp);
};
```

**Comment by ugurdogrusoz** [comment]
Finally we would like compound label font sizes to be smaller (20 -> 16).
        .selector("node[sbgnclass='compartment']")
        .css({
            'background-opacity' : '0',
            'background-color' : '#FFFFFF',
            'content' : 'data(sbgnlabel)',
            'text-valign' : 'bottom',
            'text-halign' : 'center',
            'font-size' : '14', /\* UD: changed! was 20 */
            'padding-bottom' : '20',
            'padding-top' : '20',
            'padding-left' : '20',
            'padding-right' : '20'
        })

So, we'd like the following changes:
cytoscape.renderer.canvas.sbgn-renderer.js:
Node label sizes: /3.0 -> /2.3
Info and state box label sizes: /1.0 -> /1.5

sample-app-cytoscape-sbgn.js:
Compartment label sizes: 20 -> 16

**Comment by metincansiper** [comment]
Made the addressed changes.

**Comment by ugurdogrusoz** [comment]
Funny. 2.3 was working well for ubiquitious molecules like ADP/ATP but looks like it's not. Let's change it to 2.45 instead.
cytoscape.renderer.canvas.sbgn-renderer.js:
Node label sizes: /3.0 -> /2.45 (was 2.3)
