### ISSUE TITLE
Radial layout problem

### ISSUE THREAD

**Issue by metincansiper** [metincansiper/SBGNViz_CoSE#6]
While trying to make CoSE layout working as independant from SBGNViz, we get an error in a test graph which become a forest after clearing the complex members.

**Comment by ugurdogrusoz** [comment]
Specifics? Enough for others to reproduce the error?

**Comment by metincansiper** [comment]
we tried to run this(https://github.com/ayhun/Cytoscape_improved_CoSE/blob/master/code.js) simple graph to test the layout, however, while running it in tiled mode we got error, as it became a flat forest when we clear the children of complex members. We run the graph when the incremental attribute is false and we see that the positions were undefined when the layout stoped.

**Comment by metincansiper** [comment]
The problem is solved.

**Comment by ugurdogrusoz** [comment]
Why do we have both CoSELayout.js and _CoseLayout.js in ayhun/Cytoscape_improved_CoSE/js/layout/cose?
